apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodeapp
      tier: client
  template:
    metadata:
      labels:
        app: nodeapp
        tier: client
    spec:
      containers:
        - name: nodeapp
          image: nikmassv/nodeapp:latest
